---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: "Set Facts"
      set_fact:
        vault_url: "" #https://vault_address:port
        vault_token: "" #ex. s.xxXXXXxxx
        secret_path_prefix: "/kv/data/somethingsomething/"

    - name: load variables files
      include_vars:
        file: "secret_values.yml"

    - debug:
        msg: "{{ secrets[item.key] + ' : ' + item.value }}"
      with_items: "{{ secret_values | dict2items }}"

    - name: Write a value to the secret path
      community.hashi_vault.vault_write:
        url: "{{vault_url}}"
        path: "{{secret_path_prefix}}/{{ secrets[item.key] }}"
        data:
          data:
            value: "{{item.value}}"
        auth_method: token
        token: "{{ vault_token }}"
        validate_certs: no
      with_items: "{{ secret_values | dict2items }}"
      register: result