---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: "Set Facts"
      set_fact:
        vault_url: "" #https://vault_address:port
        vault_token: "" #ex. s.xxXXXXxxx
        secret_path_prefix: "/kv/data/somethingsomething/"

    #This task wil generate an ansible variable based on the secret.key
    # ex. secrets.cluster_auth_password will generate a cluster_auth_password variable with a value of the Vault secret
    - name: Generate Variables from Vault Secrets
      set_fact:
        { "{{ item.key }}": "{{ lookup('community.hashi_vault.hashi_vault', '{{secret_path_prefix}}/{{item.value}} token={{vault_token}} url={{vault_url}}', return_format='values', validate_certs='no') }}" }
      no_log: True
      with_items: "{{secrets|dict2items}}"

    #In case we want to loop through the variables we just created
    - name: Generate vault_generated_vars from created variables
      set_fact:
        vault_generated_vars: "{{ vault_generated_vars | default({}) | combine({item.key: lookup('vars', item.key )}) }}"
      no_log: True
      with_items: "{{secrets|dict2items}}"

    - name: "We debug the contents of the vault_generated_vars - {{ item }}"
      debug:
        msg: "{{ item }}"
      with_items: "{{ vault_generated_vars | dict2items}}"
